name: Gradle Check

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [ opened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # v6.1.0
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
      # v1.5.0
      - uses: oracle-actions/setup-java@fff43251af9936a0e6a4d5d0946e14f1680e9b6b
        with:
          website: ${{ vars.JDK_SRC }}
          release: ${{ vars.GRADLE_JAVA_VERSION }}

      - name: Gradle Check
        run: ./gradlew --stacktrace -PjavaVersion=${{ steps.setup.outputs.java-version }} -PsavaGithubPackagesUsername=${{ github.actor }} -PsavaGithubPackagesPassword=${{ secrets.GITHUB_TOKEN }} check generateCatalogAsToml
        env:
          ORG_GRADLE_PROJECT_savaGithubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_savaGithubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
