name: Gradle Check PR

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: check-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check:
    if: >
      github.event.pull_request.user.login != 'sava-release-please[bot]' &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60
      - uses: oracle-actions/setup-java@fff43251af9936a0e6a4d5d0946e14f1680e9b6b
        with:
          website: ${{ vars.JDK_SRC }}
          release: ${{ vars.GRADLE_JAVA_VERSION }}

      - name: Gradle Check
        run: ./gradlew --stacktrace -PjavaVersion=${{ steps.setup.outputs.java-version }} -PsavaGithubPackagesUsername=${{ github.actor }} -PsavaGithubPackagesPassword=${{ secrets.GITHUB_TOKEN }} check generateCatalogAsToml
        env:
          ORG_GRADLE_PROJECT_savaGithubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_savaGithubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
